version: 5.1.0
variant: default
logo: /img/logo.svg
head:
    favicon: /img/favicon.svg
    manifest:
        name: liulangren blog
        short_name: 
        start_url: 
        theme_color: 
        background_color: dark
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/ppoffice/hexo-theme-icarus
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/ppoffice/hexo-theme-icarus
article:
    highlight:
        theme: monokai
        clipboard: true
        fold: unfolded
    readtime: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
comment:
    type: disqus
    shortname: ''
donates:
    -
        type: afdian
        url: ''
    -
        type: alipay
        qrcode: ''
    -
        type: buymeacoffee
        url: ''
    -
        type: patreon
        url: ''
    -
        type: paypal
        business: ''
        currency_code: USD
    -
        type: wechat
        qrcode: ''
share:
    type: sharethis
    install_url: ''
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: Hui Su
        author_title: liulangren bolg
        language: zh-CN
        location: 上海
        avatar: 
        avatar_rounded: false
        gravatar: 
        follow_link: https://github.com/liulangrenaaa
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/liulangrenaaa
    -
        position: left
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        position: left
        type: links
        links:
            Google: https://www.google.com.hk/
            LKML: https://lkml.org/
            Gmail: https://mail.google.com/mail
            Github: https://github.com/
            Gitee: https://gitee.com/
            知乎: https://www.zhihu.com/explore
            Leetcode 剑指offer: https://leetcode-cn.com/contest/
            Leetcode 周赛: https://leetcode-cn.com/problemset/lcof/
            百度分析: https://tongji.baidu.com/web/32051076/overview/index?siteId=16230094
            google分析: https://analytics.google.com/analytics/web/#/a187909645p259761261/admin/streams/table/
    -
        position: right
        type: archives
    -
        position: right
        type: categories
    -
        position: right
        type: recent_posts
    -
        position: left
        type: tags
    -
        position: left
        type: subscribe_email
        description: 
        feedburner_id: ''
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: cabdc5b9b70bb83fa919a6ebeb439f93
    bing_webmaster:
        tracking_id: 
    busuanzi: true
    cnzz:
        id: 
        web_id: 
    gallery: true
    google_analytics:
        tracking_id: PTKX6HMR55
    hotjar:
        site_id: 
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 
providers:
    cdn: loli
    fontcdn: loli
    iconcdn: loli
